// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: plugin.proto

package pluginv1

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BackendPlugin_Capabilities_FullMethodName = "/plugin.v1.BackendPlugin/Capabilities"
	BackendPlugin_Create_FullMethodName       = "/plugin.v1.BackendPlugin/Create"
	BackendPlugin_Start_FullMethodName        = "/plugin.v1.BackendPlugin/Start"
	BackendPlugin_Exec_FullMethodName         = "/plugin.v1.BackendPlugin/Exec"
	BackendPlugin_CopyIn_FullMethodName       = "/plugin.v1.BackendPlugin/CopyIn"
	BackendPlugin_CopyLocal_FullMethodName    = "/plugin.v1.BackendPlugin/CopyLocal"
	BackendPlugin_CopyOut_FullMethodName      = "/plugin.v1.BackendPlugin/CopyOut"
	BackendPlugin_UpdateEnv_FullMethodName    = "/plugin.v1.BackendPlugin/UpdateEnv"
	BackendPlugin_IsHealthy_FullMethodName    = "/plugin.v1.BackendPlugin/IsHealthy"
	BackendPlugin_Remove_FullMethodName       = "/plugin.v1.BackendPlugin/Remove"
)

// BackendPluginClient is the client API for BackendPlugin service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// BackendPlugin owns the full lifecycle of an execution environment and every
// container operation within it.
type BackendPluginClient interface {
	// Capabilities returns the backend's name, filesystem layout, and feature
	// flags. The runner calls it once at connection time.
	Capabilities(ctx context.Context, in *CapabilitiesRequest, opts ...grpc.CallOption) (*CapabilitiesResponse, error)
	// Create provisions a new execution environment. Image pulling is folded in
	// (see force_pull); service containers are passed here so the backend can
	// realise them however fits its platform.
	Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*CreateResponse, error)
	// Start boots a previously created environment.
	Start(ctx context.Context, in *StartRequest, opts ...grpc.CallOption) (*StartResponse, error)
	// Exec runs a command inside the environment, streaming stdout/stderr back.
	Exec(ctx context.Context, in *ExecRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ExecOutput], error)
	// CopyIn transfers a tar archive into the environment.
	CopyIn(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[CopyInChunk, CopyInResponse], error)
	// CopyLocal copies a path from a volume shared with the runner into the
	// environment. Only called when CapabilitiesResponse.supports_local_copy is
	// true; a faster alternative to streaming the same bytes through CopyIn.
	CopyLocal(ctx context.Context, in *CopyLocalRequest, opts ...grpc.CallOption) (*CopyLocalResponse, error)
	// CopyOut transfers a tar archive out of the environment.
	CopyOut(ctx context.Context, in *CopyOutRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[CopyOutChunk], error)
	// UpdateEnv reads an env file inside the environment and returns the parsed
	// variables merged over the ones the runner already knows.
	UpdateEnv(ctx context.Context, in *UpdateEnvRequest, opts ...grpc.CallOption) (*UpdateEnvResponse, error)
	// IsHealthy checks whether the environment is still running.
	IsHealthy(ctx context.Context, in *IsHealthyRequest, opts ...grpc.CallOption) (*IsHealthyResponse, error)
	// Remove tears down the environment and releases all resources.
	Remove(ctx context.Context, in *RemoveRequest, opts ...grpc.CallOption) (*RemoveResponse, error)
}

type backendPluginClient struct {
	cc grpc.ClientConnInterface
}

func NewBackendPluginClient(cc grpc.ClientConnInterface) BackendPluginClient {
	return &backendPluginClient{cc}
}

func (c *backendPluginClient) Capabilities(ctx context.Context, in *CapabilitiesRequest, opts ...grpc.CallOption) (*CapabilitiesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CapabilitiesResponse)
	err := c.cc.Invoke(ctx, BackendPlugin_Capabilities_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backendPluginClient) Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*CreateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateResponse)
	err := c.cc.Invoke(ctx, BackendPlugin_Create_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backendPluginClient) Start(ctx context.Context, in *StartRequest, opts ...grpc.CallOption) (*StartResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StartResponse)
	err := c.cc.Invoke(ctx, BackendPlugin_Start_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backendPluginClient) Exec(ctx context.Context, in *ExecRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ExecOutput], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &BackendPlugin_ServiceDesc.Streams[0], BackendPlugin_Exec_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ExecRequest, ExecOutput]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type BackendPlugin_ExecClient = grpc.ServerStreamingClient[ExecOutput]

func (c *backendPluginClient) CopyIn(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[CopyInChunk, CopyInResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &BackendPlugin_ServiceDesc.Streams[1], BackendPlugin_CopyIn_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[CopyInChunk, CopyInResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type BackendPlugin_CopyInClient = grpc.ClientStreamingClient[CopyInChunk, CopyInResponse]

func (c *backendPluginClient) CopyLocal(ctx context.Context, in *CopyLocalRequest, opts ...grpc.CallOption) (*CopyLocalResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CopyLocalResponse)
	err := c.cc.Invoke(ctx, BackendPlugin_CopyLocal_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backendPluginClient) CopyOut(ctx context.Context, in *CopyOutRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[CopyOutChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &BackendPlugin_ServiceDesc.Streams[2], BackendPlugin_CopyOut_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[CopyOutRequest, CopyOutChunk]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type BackendPlugin_CopyOutClient = grpc.ServerStreamingClient[CopyOutChunk]

func (c *backendPluginClient) UpdateEnv(ctx context.Context, in *UpdateEnvRequest, opts ...grpc.CallOption) (*UpdateEnvResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateEnvResponse)
	err := c.cc.Invoke(ctx, BackendPlugin_UpdateEnv_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backendPluginClient) IsHealthy(ctx context.Context, in *IsHealthyRequest, opts ...grpc.CallOption) (*IsHealthyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IsHealthyResponse)
	err := c.cc.Invoke(ctx, BackendPlugin_IsHealthy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backendPluginClient) Remove(ctx context.Context, in *RemoveRequest, opts ...grpc.CallOption) (*RemoveResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemoveResponse)
	err := c.cc.Invoke(ctx, BackendPlugin_Remove_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BackendPluginServer is the server API for BackendPlugin service.
// All implementations must embed UnimplementedBackendPluginServer
// for forward compatibility.
//
// BackendPlugin owns the full lifecycle of an execution environment and every
// container operation within it.
type BackendPluginServer interface {
	// Capabilities returns the backend's name, filesystem layout, and feature
	// flags. The runner calls it once at connection time.
	Capabilities(context.Context, *CapabilitiesRequest) (*CapabilitiesResponse, error)
	// Create provisions a new execution environment. Image pulling is folded in
	// (see force_pull); service containers are passed here so the backend can
	// realise them however fits its platform.
	Create(context.Context, *CreateRequest) (*CreateResponse, error)
	// Start boots a previously created environment.
	Start(context.Context, *StartRequest) (*StartResponse, error)
	// Exec runs a command inside the environment, streaming stdout/stderr back.
	Exec(*ExecRequest, grpc.ServerStreamingServer[ExecOutput]) error
	// CopyIn transfers a tar archive into the environment.
	CopyIn(grpc.ClientStreamingServer[CopyInChunk, CopyInResponse]) error
	// CopyLocal copies a path from a volume shared with the runner into the
	// environment. Only called when CapabilitiesResponse.supports_local_copy is
	// true; a faster alternative to streaming the same bytes through CopyIn.
	CopyLocal(context.Context, *CopyLocalRequest) (*CopyLocalResponse, error)
	// CopyOut transfers a tar archive out of the environment.
	CopyOut(*CopyOutRequest, grpc.ServerStreamingServer[CopyOutChunk]) error
	// UpdateEnv reads an env file inside the environment and returns the parsed
	// variables merged over the ones the runner already knows.
	UpdateEnv(context.Context, *UpdateEnvRequest) (*UpdateEnvResponse, error)
	// IsHealthy checks whether the environment is still running.
	IsHealthy(context.Context, *IsHealthyRequest) (*IsHealthyResponse, error)
	// Remove tears down the environment and releases all resources.
	Remove(context.Context, *RemoveRequest) (*RemoveResponse, error)
	mustEmbedUnimplementedBackendPluginServer()
}

// UnimplementedBackendPluginServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBackendPluginServer struct{}

func (UnimplementedBackendPluginServer) Capabilities(context.Context, *CapabilitiesRequest) (*CapabilitiesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Capabilities not implemented")
}

func (UnimplementedBackendPluginServer) Create(context.Context, *CreateRequest) (*CreateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Create not implemented")
}

func (UnimplementedBackendPluginServer) Start(context.Context, *StartRequest) (*StartResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Start not implemented")
}

func (UnimplementedBackendPluginServer) Exec(*ExecRequest, grpc.ServerStreamingServer[ExecOutput]) error {
	return status.Error(codes.Unimplemented, "method Exec not implemented")
}

func (UnimplementedBackendPluginServer) CopyIn(grpc.ClientStreamingServer[CopyInChunk, CopyInResponse]) error {
	return status.Error(codes.Unimplemented, "method CopyIn not implemented")
}

func (UnimplementedBackendPluginServer) CopyLocal(context.Context, *CopyLocalRequest) (*CopyLocalResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CopyLocal not implemented")
}

func (UnimplementedBackendPluginServer) CopyOut(*CopyOutRequest, grpc.ServerStreamingServer[CopyOutChunk]) error {
	return status.Error(codes.Unimplemented, "method CopyOut not implemented")
}

func (UnimplementedBackendPluginServer) UpdateEnv(context.Context, *UpdateEnvRequest) (*UpdateEnvResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateEnv not implemented")
}

func (UnimplementedBackendPluginServer) IsHealthy(context.Context, *IsHealthyRequest) (*IsHealthyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method IsHealthy not implemented")
}

func (UnimplementedBackendPluginServer) Remove(context.Context, *RemoveRequest) (*RemoveResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Remove not implemented")
}
func (UnimplementedBackendPluginServer) mustEmbedUnimplementedBackendPluginServer() {}
func (UnimplementedBackendPluginServer) testEmbeddedByValue()                       {}

// UnsafeBackendPluginServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BackendPluginServer will
// result in compilation errors.
type UnsafeBackendPluginServer interface {
	mustEmbedUnimplementedBackendPluginServer()
}

func RegisterBackendPluginServer(s grpc.ServiceRegistrar, srv BackendPluginServer) {
	// If the following call panics, it indicates UnimplementedBackendPluginServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BackendPlugin_ServiceDesc, srv)
}

func _BackendPlugin_Capabilities_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CapabilitiesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackendPluginServer).Capabilities(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BackendPlugin_Capabilities_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackendPluginServer).Capabilities(ctx, req.(*CapabilitiesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BackendPlugin_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackendPluginServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BackendPlugin_Create_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackendPluginServer).Create(ctx, req.(*CreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BackendPlugin_Start_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackendPluginServer).Start(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BackendPlugin_Start_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackendPluginServer).Start(ctx, req.(*StartRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BackendPlugin_Exec_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ExecRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(BackendPluginServer).Exec(m, &grpc.GenericServerStream[ExecRequest, ExecOutput]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type BackendPlugin_ExecServer = grpc.ServerStreamingServer[ExecOutput]

func _BackendPlugin_CopyIn_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(BackendPluginServer).CopyIn(&grpc.GenericServerStream[CopyInChunk, CopyInResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type BackendPlugin_CopyInServer = grpc.ClientStreamingServer[CopyInChunk, CopyInResponse]

func _BackendPlugin_CopyLocal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CopyLocalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackendPluginServer).CopyLocal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BackendPlugin_CopyLocal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackendPluginServer).CopyLocal(ctx, req.(*CopyLocalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BackendPlugin_CopyOut_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(CopyOutRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(BackendPluginServer).CopyOut(m, &grpc.GenericServerStream[CopyOutRequest, CopyOutChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type BackendPlugin_CopyOutServer = grpc.ServerStreamingServer[CopyOutChunk]

func _BackendPlugin_UpdateEnv_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateEnvRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackendPluginServer).UpdateEnv(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BackendPlugin_UpdateEnv_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackendPluginServer).UpdateEnv(ctx, req.(*UpdateEnvRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BackendPlugin_IsHealthy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IsHealthyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackendPluginServer).IsHealthy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BackendPlugin_IsHealthy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackendPluginServer).IsHealthy(ctx, req.(*IsHealthyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BackendPlugin_Remove_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackendPluginServer).Remove(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BackendPlugin_Remove_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackendPluginServer).Remove(ctx, req.(*RemoveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BackendPlugin_ServiceDesc is the grpc.ServiceDesc for BackendPlugin service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BackendPlugin_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "plugin.v1.BackendPlugin",
	HandlerType: (*BackendPluginServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Capabilities",
			Handler:    _BackendPlugin_Capabilities_Handler,
		},
		{
			MethodName: "Create",
			Handler:    _BackendPlugin_Create_Handler,
		},
		{
			MethodName: "Start",
			Handler:    _BackendPlugin_Start_Handler,
		},
		{
			MethodName: "CopyLocal",
			Handler:    _BackendPlugin_CopyLocal_Handler,
		},
		{
			MethodName: "UpdateEnv",
			Handler:    _BackendPlugin_UpdateEnv_Handler,
		},
		{
			MethodName: "IsHealthy",
			Handler:    _BackendPlugin_IsHealthy_Handler,
		},
		{
			MethodName: "Remove",
			Handler:    _BackendPlugin_Remove_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Exec",
			Handler:       _BackendPlugin_Exec_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "CopyIn",
			Handler:       _BackendPlugin_CopyIn_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "CopyOut",
			Handler:       _BackendPlugin_CopyOut_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "plugin.proto",
}

const (
	DockerTunnelPlugin_Capabilities_FullMethodName = "/plugin.v1.DockerTunnelPlugin/Capabilities"
	DockerTunnelPlugin_Create_FullMethodName       = "/plugin.v1.DockerTunnelPlugin/Create"
	DockerTunnelPlugin_Remove_FullMethodName       = "/plugin.v1.DockerTunnelPlugin/Remove"
)

// DockerTunnelPluginClient is the client API for DockerTunnelPlugin service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// DockerTunnelPlugin boots an environment that exposes a Docker daemon and
// hands the runner the endpoint to drive it. The runner's built-in Docker
// back-end then creates the job, service, and step containers against that
// daemon, so a VM backend (Tart, QEMU, Firecracker, ...) reuses the whole
// Docker driver instead of reimplementing exec/copy over its own transport.
type DockerTunnelPluginClient interface {
	// Capabilities returns the plugin's identity and protocol version. It carries
	// none of the filesystem/feature fields of a BackendPlugin: the runner learns
	// those from the Docker daemon the plugin exposes.
	Capabilities(ctx context.Context, in *CapabilitiesRequest, opts ...grpc.CallOption) (*TunnelCapabilitiesResponse, error)
	// Create boots the environment and returns the Docker endpoint to drive.
	Create(ctx context.Context, in *TunnelCreateRequest, opts ...grpc.CallOption) (*TunnelCreateResponse, error)
	// Remove tears the environment down.
	Remove(ctx context.Context, in *RemoveRequest, opts ...grpc.CallOption) (*RemoveResponse, error)
}

type dockerTunnelPluginClient struct {
	cc grpc.ClientConnInterface
}

func NewDockerTunnelPluginClient(cc grpc.ClientConnInterface) DockerTunnelPluginClient {
	return &dockerTunnelPluginClient{cc}
}

func (c *dockerTunnelPluginClient) Capabilities(ctx context.Context, in *CapabilitiesRequest, opts ...grpc.CallOption) (*TunnelCapabilitiesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TunnelCapabilitiesResponse)
	err := c.cc.Invoke(ctx, DockerTunnelPlugin_Capabilities_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dockerTunnelPluginClient) Create(ctx context.Context, in *TunnelCreateRequest, opts ...grpc.CallOption) (*TunnelCreateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TunnelCreateResponse)
	err := c.cc.Invoke(ctx, DockerTunnelPlugin_Create_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dockerTunnelPluginClient) Remove(ctx context.Context, in *RemoveRequest, opts ...grpc.CallOption) (*RemoveResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemoveResponse)
	err := c.cc.Invoke(ctx, DockerTunnelPlugin_Remove_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DockerTunnelPluginServer is the server API for DockerTunnelPlugin service.
// All implementations must embed UnimplementedDockerTunnelPluginServer
// for forward compatibility.
//
// DockerTunnelPlugin boots an environment that exposes a Docker daemon and
// hands the runner the endpoint to drive it. The runner's built-in Docker
// back-end then creates the job, service, and step containers against that
// daemon, so a VM backend (Tart, QEMU, Firecracker, ...) reuses the whole
// Docker driver instead of reimplementing exec/copy over its own transport.
type DockerTunnelPluginServer interface {
	// Capabilities returns the plugin's identity and protocol version. It carries
	// none of the filesystem/feature fields of a BackendPlugin: the runner learns
	// those from the Docker daemon the plugin exposes.
	Capabilities(context.Context, *CapabilitiesRequest) (*TunnelCapabilitiesResponse, error)
	// Create boots the environment and returns the Docker endpoint to drive.
	Create(context.Context, *TunnelCreateRequest) (*TunnelCreateResponse, error)
	// Remove tears the environment down.
	Remove(context.Context, *RemoveRequest) (*RemoveResponse, error)
	mustEmbedUnimplementedDockerTunnelPluginServer()
}

// UnimplementedDockerTunnelPluginServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDockerTunnelPluginServer struct{}

func (UnimplementedDockerTunnelPluginServer) Capabilities(context.Context, *CapabilitiesRequest) (*TunnelCapabilitiesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Capabilities not implemented")
}

func (UnimplementedDockerTunnelPluginServer) Create(context.Context, *TunnelCreateRequest) (*TunnelCreateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Create not implemented")
}

func (UnimplementedDockerTunnelPluginServer) Remove(context.Context, *RemoveRequest) (*RemoveResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Remove not implemented")
}
func (UnimplementedDockerTunnelPluginServer) mustEmbedUnimplementedDockerTunnelPluginServer() {}
func (UnimplementedDockerTunnelPluginServer) testEmbeddedByValue()                            {}

// UnsafeDockerTunnelPluginServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DockerTunnelPluginServer will
// result in compilation errors.
type UnsafeDockerTunnelPluginServer interface {
	mustEmbedUnimplementedDockerTunnelPluginServer()
}

func RegisterDockerTunnelPluginServer(s grpc.ServiceRegistrar, srv DockerTunnelPluginServer) {
	// If the following call panics, it indicates UnimplementedDockerTunnelPluginServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DockerTunnelPlugin_ServiceDesc, srv)
}

func _DockerTunnelPlugin_Capabilities_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CapabilitiesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DockerTunnelPluginServer).Capabilities(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DockerTunnelPlugin_Capabilities_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DockerTunnelPluginServer).Capabilities(ctx, req.(*CapabilitiesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DockerTunnelPlugin_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TunnelCreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DockerTunnelPluginServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DockerTunnelPlugin_Create_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DockerTunnelPluginServer).Create(ctx, req.(*TunnelCreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DockerTunnelPlugin_Remove_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DockerTunnelPluginServer).Remove(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DockerTunnelPlugin_Remove_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DockerTunnelPluginServer).Remove(ctx, req.(*RemoveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DockerTunnelPlugin_ServiceDesc is the grpc.ServiceDesc for DockerTunnelPlugin service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DockerTunnelPlugin_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "plugin.v1.DockerTunnelPlugin",
	HandlerType: (*DockerTunnelPluginServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Capabilities",
			Handler:    _DockerTunnelPlugin_Capabilities_Handler,
		},
		{
			MethodName: "Create",
			Handler:    _DockerTunnelPlugin_Create_Handler,
		},
		{
			MethodName: "Remove",
			Handler:    _DockerTunnelPlugin_Remove_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "plugin.proto",
}
