// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: plugin.proto

package pluginv1

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ExecOutput_Stream int32

const (
	ExecOutput_STDOUT ExecOutput_Stream = 0
	ExecOutput_STDERR ExecOutput_Stream = 1
)

// Enum value maps for ExecOutput_Stream.
var (
	ExecOutput_Stream_name = map[int32]string{
		0: "STDOUT",
		1: "STDERR",
	}
	ExecOutput_Stream_value = map[string]int32{
		"STDOUT": 0,
		"STDERR": 1,
	}
)

func (x ExecOutput_Stream) Enum() *ExecOutput_Stream {
	p := new(ExecOutput_Stream)
	*p = x
	return p
}

func (x ExecOutput_Stream) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ExecOutput_Stream) Descriptor() protoreflect.EnumDescriptor {
	return file_plugin_proto_enumTypes[0].Descriptor()
}

func (ExecOutput_Stream) Type() protoreflect.EnumType {
	return &file_plugin_proto_enumTypes[0]
}

func (x ExecOutput_Stream) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ExecOutput_Stream.Descriptor instead.
func (ExecOutput_Stream) EnumDescriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{12, 0}
}

type CapabilitiesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CapabilitiesRequest) Reset() {
	*x = CapabilitiesRequest{}
	mi := &file_plugin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CapabilitiesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CapabilitiesRequest) ProtoMessage() {}

func (x *CapabilitiesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CapabilitiesRequest.ProtoReflect.Descriptor instead.
func (*CapabilitiesRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{0}
}

type CapabilitiesResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// name identifies the backend (e.g. "kubernetes"); used in logs and as the
	// container back-end name.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// root_path is the base directory the runner lays workflow files out under.
	RootPath string `protobuf:"bytes,2,opt,name=root_path,json=rootPath,proto3" json:"root_path,omitempty"`
	// act_path is where the runner stages its helper binaries and action code.
	ActPath string `protobuf:"bytes,3,opt,name=act_path,json=actPath,proto3" json:"act_path,omitempty"`
	// tool_cache_path is exposed to jobs as RUNNER_TOOL_CACHE.
	ToolCachePath string `protobuf:"bytes,4,opt,name=tool_cache_path,json=toolCachePath,proto3" json:"tool_cache_path,omitempty"`
	// path_variable_name is the search-path environment variable ("PATH" on
	// POSIX, "Path" on Windows). Defaults to "PATH" when empty.
	PathVariableName string `protobuf:"bytes,5,opt,name=path_variable_name,json=pathVariableName,proto3" json:"path_variable_name,omitempty"`
	// default_path_variable is the search path used when a job sets none.
	DefaultPathVariable string `protobuf:"bytes,6,opt,name=default_path_variable,json=defaultPathVariable,proto3" json:"default_path_variable,omitempty"`
	// path_separator joins entries of path_variable_name (":" or ";"). Defaults
	// to ":" when empty.
	PathSeparator string `protobuf:"bytes,7,opt,name=path_separator,json=pathSeparator,proto3" json:"path_separator,omitempty"`
	// supports_docker_actions gates `uses: docker://` and container actions. When
	// false, the runner errors upfront on a job that needs them.
	SupportsDockerActions bool `protobuf:"varint,8,opt,name=supports_docker_actions,json=supportsDockerActions,proto3" json:"supports_docker_actions,omitempty"`
	// manages_own_networking tells the runner the backend provides connectivity
	// itself; the runner then skips creating/attaching a Docker-style network.
	ManagesOwnNetworking bool `protobuf:"varint,9,opt,name=manages_own_networking,json=managesOwnNetworking,proto3" json:"manages_own_networking,omitempty"`
	// supports_service_containers gates the workflow `services:` block. When
	// false, the runner errors upfront on a job that declares services.
	SupportsServiceContainers bool `protobuf:"varint,10,opt,name=supports_service_containers,json=supportsServiceContainers,proto3" json:"supports_service_containers,omitempty"`
	// environment_case_insensitive marks environments whose variable names are
	// case-insensitive (Windows), so the runner de-duplicates accordingly.
	EnvironmentCaseInsensitive bool `protobuf:"varint,11,opt,name=environment_case_insensitive,json=environmentCaseInsensitive,proto3" json:"environment_case_insensitive,omitempty"`
	// runner_context carries backend-provided values for the Actions runner
	// context (os, arch, temp, tool_cache). Treated as opaque key/values.
	RunnerContext map[string]string `protobuf:"bytes,12,rep,name=runner_context,json=runnerContext,proto3" json:"runner_context,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// supports_local_copy advertises the CopyLocal fast path (a volume shared
	// between runner and environment). When false the runner uses CopyIn.
	SupportsLocalCopy bool `protobuf:"varint,13,opt,name=supports_local_copy,json=supportsLocalCopy,proto3" json:"supports_local_copy,omitempty"`
	// protocol_version is the plugin protocol the server speaks. The runner
	// rejects a plugin whose version it does not support.
	ProtocolVersion uint32 `protobuf:"varint,15,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CapabilitiesResponse) Reset() {
	*x = CapabilitiesResponse{}
	mi := &file_plugin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CapabilitiesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CapabilitiesResponse) ProtoMessage() {}

func (x *CapabilitiesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CapabilitiesResponse.ProtoReflect.Descriptor instead.
func (*CapabilitiesResponse) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{1}
}

func (x *CapabilitiesResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CapabilitiesResponse) GetRootPath() string {
	if x != nil {
		return x.RootPath
	}
	return ""
}

func (x *CapabilitiesResponse) GetActPath() string {
	if x != nil {
		return x.ActPath
	}
	return ""
}

func (x *CapabilitiesResponse) GetToolCachePath() string {
	if x != nil {
		return x.ToolCachePath
	}
	return ""
}

func (x *CapabilitiesResponse) GetPathVariableName() string {
	if x != nil {
		return x.PathVariableName
	}
	return ""
}

func (x *CapabilitiesResponse) GetDefaultPathVariable() string {
	if x != nil {
		return x.DefaultPathVariable
	}
	return ""
}

func (x *CapabilitiesResponse) GetPathSeparator() string {
	if x != nil {
		return x.PathSeparator
	}
	return ""
}

func (x *CapabilitiesResponse) GetSupportsDockerActions() bool {
	if x != nil {
		return x.SupportsDockerActions
	}
	return false
}

func (x *CapabilitiesResponse) GetManagesOwnNetworking() bool {
	if x != nil {
		return x.ManagesOwnNetworking
	}
	return false
}

func (x *CapabilitiesResponse) GetSupportsServiceContainers() bool {
	if x != nil {
		return x.SupportsServiceContainers
	}
	return false
}

func (x *CapabilitiesResponse) GetEnvironmentCaseInsensitive() bool {
	if x != nil {
		return x.EnvironmentCaseInsensitive
	}
	return false
}

func (x *CapabilitiesResponse) GetRunnerContext() map[string]string {
	if x != nil {
		return x.RunnerContext
	}
	return nil
}

func (x *CapabilitiesResponse) GetSupportsLocalCopy() bool {
	if x != nil {
		return x.SupportsLocalCopy
	}
	return false
}

func (x *CapabilitiesResponse) GetProtocolVersion() uint32 {
	if x != nil {
		return x.ProtocolVersion
	}
	return 0
}

type ServiceContainer struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// name is the service ID from the workflow `services:` block.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// image is the backend-defined image reference for the service.
	Image string `protobuf:"bytes,2,opt,name=image,proto3" json:"image,omitempty"`
	// env are the service container's environment variables.
	Env map[string]string `protobuf:"bytes,3,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// ports are host:container port mappings requested for the service.
	Ports         []string `protobuf:"bytes,4,rep,name=ports,proto3" json:"ports,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceContainer) Reset() {
	*x = ServiceContainer{}
	mi := &file_plugin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceContainer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceContainer) ProtoMessage() {}

func (x *ServiceContainer) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceContainer.ProtoReflect.Descriptor instead.
func (*ServiceContainer) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{2}
}

func (x *ServiceContainer) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ServiceContainer) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *ServiceContainer) GetEnv() map[string]string {
	if x != nil {
		return x.Env
	}
	return nil
}

func (x *ServiceContainer) GetPorts() []string {
	if x != nil {
		return x.Ports
	}
	return nil
}

type CreateRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// image is the backend-defined reference for the job container image. It is
	// opaque to the protocol; a Docker backend reads it as a Docker image name,
	// another backend may read it as a VM template, etc.
	Image string `protobuf:"bytes,1,opt,name=image,proto3" json:"image,omitempty"`
	// name is a runner-assigned handle for the environment, unique per job.
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// env are the environment variables to seed the job container with.
	Env map[string]string `protobuf:"bytes,3,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// working_dir is the directory commands run in by default.
	WorkingDir string `protobuf:"bytes,4,opt,name=working_dir,json=workingDir,proto3" json:"working_dir,omitempty"`
	// cap_add / cap_drop are Linux container capability adjustments. Backends
	// that cannot express them (non-container executors) may ignore them.
	CapAdd  []string `protobuf:"bytes,5,rep,name=cap_add,json=capAdd,proto3" json:"cap_add,omitempty"`
	CapDrop []string `protobuf:"bytes,6,rep,name=cap_drop,json=capDrop,proto3" json:"cap_drop,omitempty"`
	// services are the service containers to bring up alongside the job. Only
	// populated when CapabilitiesResponse.supports_service_containers is true.
	Services []*ServiceContainer `protobuf:"bytes,7,rep,name=services,proto3" json:"services,omitempty"`
	// backend_options are opaque, backend-specific options taken verbatim from
	// the runner's per-label plugin configuration (e.g. namespace, VM flavour).
	BackendOptions map[string]string `protobuf:"bytes,8,rep,name=backend_options,json=backendOptions,proto3" json:"backend_options,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// force_pull asks the backend to re-fetch the image rather than use a cached
	// copy. Backends that cannot honor it should still succeed with the cache.
	ForcePull bool `protobuf:"varint,9,opt,name=force_pull,json=forcePull,proto3" json:"force_pull,omitempty"`
	// platform is an execution-environment-specific value the runner passes
	// through verbatim (a Docker backend reads it as an OS/arch string like
	// "linux/amd64"). Omitted when the runner has no selection to convey.
	// Platform discovery is being reworked; this field is provisional.
	Platform      *string `protobuf:"bytes,10,opt,name=platform,proto3,oneof" json:"platform,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRequest) Reset() {
	*x = CreateRequest{}
	mi := &file_plugin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRequest) ProtoMessage() {}

func (x *CreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRequest.ProtoReflect.Descriptor instead.
func (*CreateRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{3}
}

func (x *CreateRequest) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *CreateRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateRequest) GetEnv() map[string]string {
	if x != nil {
		return x.Env
	}
	return nil
}

func (x *CreateRequest) GetWorkingDir() string {
	if x != nil {
		return x.WorkingDir
	}
	return ""
}

func (x *CreateRequest) GetCapAdd() []string {
	if x != nil {
		return x.CapAdd
	}
	return nil
}

func (x *CreateRequest) GetCapDrop() []string {
	if x != nil {
		return x.CapDrop
	}
	return nil
}

func (x *CreateRequest) GetServices() []*ServiceContainer {
	if x != nil {
		return x.Services
	}
	return nil
}

func (x *CreateRequest) GetBackendOptions() map[string]string {
	if x != nil {
		return x.BackendOptions
	}
	return nil
}

func (x *CreateRequest) GetForcePull() bool {
	if x != nil {
		return x.ForcePull
	}
	return false
}

func (x *CreateRequest) GetPlatform() string {
	if x != nil && x.Platform != nil {
		return *x.Platform
	}
	return ""
}

type CreateResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// environment_id is the handle for all later RPCs targeting this environment.
	EnvironmentId string `protobuf:"bytes,1,opt,name=environment_id,json=environmentId,proto3" json:"environment_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateResponse) Reset() {
	*x = CreateResponse{}
	mi := &file_plugin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateResponse) ProtoMessage() {}

func (x *CreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateResponse.ProtoReflect.Descriptor instead.
func (*CreateResponse) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{4}
}

func (x *CreateResponse) GetEnvironmentId() string {
	if x != nil {
		return x.EnvironmentId
	}
	return ""
}

// DockerDelegate carries the address and TLS material for a Docker daemon a
// DockerTunnelPlugin exposes (e.g. one running inside a VM it booted).
//
// Trust model: the runner already trusts the plugin (it is configured to talk
// to it). TLS here does not protect the runner from the plugin; it protects the
// daemon socket from other parties on the environment's network. So:
//   - Prefer a non-networked endpoint (unix:// socket, vsock, or an SSH tunnel
//     the plugin sets up). Then no TLS material is needed and the fields below
//     stay empty.
//   - Only when the daemon must be reached over a real network should the
//     plugin supply TLS material, and it should be EPHEMERAL client credentials
//     scoped to this one throwaway environment (minted at Create, discarded at
//     Remove) rather than a long-lived or shared identity.
//
// All bytes fields are PEM-encoded.
type DockerDelegate struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// endpoint is the daemon address: unix://path, tcp://host:port, or ssh://.
	Endpoint string `protobuf:"bytes,1,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	// tls_ca is the CA certificate (public) used to verify the daemon. Empty for
	// non-networked endpoints.
	TlsCa []byte `protobuf:"bytes,2,opt,name=tls_ca,json=tlsCa,proto3" json:"tls_ca,omitempty"`
	// tls_cert / tls_key are the client certificate and its private key the
	// runner presents to the daemon. Empty for non-networked endpoints; when set,
	// should be ephemeral and scoped to this environment (see message docs).
	TlsCert []byte `protobuf:"bytes,3,opt,name=tls_cert,json=tlsCert,proto3" json:"tls_cert,omitempty"`
	TlsKey  []byte `protobuf:"bytes,4,opt,name=tls_key,json=tlsKey,proto3" json:"tls_key,omitempty"`
	// tls_insecure_skip_verify disables certificate verification. Intended for
	// development and bootstrap scenarios with self-signed daemons only.
	TlsInsecureSkipVerify bool `protobuf:"varint,5,opt,name=tls_insecure_skip_verify,json=tlsInsecureSkipVerify,proto3" json:"tls_insecure_skip_verify,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *DockerDelegate) Reset() {
	*x = DockerDelegate{}
	mi := &file_plugin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DockerDelegate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DockerDelegate) ProtoMessage() {}

func (x *DockerDelegate) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DockerDelegate.ProtoReflect.Descriptor instead.
func (*DockerDelegate) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{5}
}

func (x *DockerDelegate) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *DockerDelegate) GetTlsCa() []byte {
	if x != nil {
		return x.TlsCa
	}
	return nil
}

func (x *DockerDelegate) GetTlsCert() []byte {
	if x != nil {
		return x.TlsCert
	}
	return nil
}

func (x *DockerDelegate) GetTlsKey() []byte {
	if x != nil {
		return x.TlsKey
	}
	return nil
}

func (x *DockerDelegate) GetTlsInsecureSkipVerify() bool {
	if x != nil {
		return x.TlsInsecureSkipVerify
	}
	return false
}

type TunnelCapabilitiesResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// name identifies the tunnel plugin (e.g. "tart"); used in logs.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// protocol_version is the plugin protocol the server speaks. The runner
	// rejects a plugin whose version it does not support.
	ProtocolVersion uint32 `protobuf:"varint,2,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *TunnelCapabilitiesResponse) Reset() {
	*x = TunnelCapabilitiesResponse{}
	mi := &file_plugin_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TunnelCapabilitiesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TunnelCapabilitiesResponse) ProtoMessage() {}

func (x *TunnelCapabilitiesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TunnelCapabilitiesResponse.ProtoReflect.Descriptor instead.
func (*TunnelCapabilitiesResponse) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{6}
}

func (x *TunnelCapabilitiesResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TunnelCapabilitiesResponse) GetProtocolVersion() uint32 {
	if x != nil {
		return x.ProtocolVersion
	}
	return 0
}

type TunnelCreateRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// backend_options are opaque, backend-specific options taken verbatim from
	// the runner's per-label plugin configuration (e.g. VM flavour, base image).
	BackendOptions map[string]string `protobuf:"bytes,1,rep,name=backend_options,json=backendOptions,proto3" json:"backend_options,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// platform is an execution-environment-specific value passed through verbatim
	// (which VM/OS to boot). Omitted when the runner has no selection to convey.
	// Platform discovery is being reworked; this field is provisional.
	Platform *string `protobuf:"bytes,2,opt,name=platform,proto3,oneof" json:"platform,omitempty"`
	// force_pull asks the plugin to refresh its base image (e.g. VM template)
	// rather than use a cached copy. Plugins that cannot honor it should still
	// succeed with the cache.
	ForcePull     bool `protobuf:"varint,3,opt,name=force_pull,json=forcePull,proto3" json:"force_pull,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TunnelCreateRequest) Reset() {
	*x = TunnelCreateRequest{}
	mi := &file_plugin_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TunnelCreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TunnelCreateRequest) ProtoMessage() {}

func (x *TunnelCreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TunnelCreateRequest.ProtoReflect.Descriptor instead.
func (*TunnelCreateRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{7}
}

func (x *TunnelCreateRequest) GetBackendOptions() map[string]string {
	if x != nil {
		return x.BackendOptions
	}
	return nil
}

func (x *TunnelCreateRequest) GetPlatform() string {
	if x != nil && x.Platform != nil {
		return *x.Platform
	}
	return ""
}

func (x *TunnelCreateRequest) GetForcePull() bool {
	if x != nil {
		return x.ForcePull
	}
	return false
}

type TunnelCreateResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// environment_id is the handle passed to Remove to tear the environment down.
	EnvironmentId string `protobuf:"bytes,1,opt,name=environment_id,json=environmentId,proto3" json:"environment_id,omitempty"`
	// delegate is the Docker daemon the runner drives containers against. Always
	// set on a successful Create.
	Delegate      *DockerDelegate `protobuf:"bytes,2,opt,name=delegate,proto3" json:"delegate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TunnelCreateResponse) Reset() {
	*x = TunnelCreateResponse{}
	mi := &file_plugin_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TunnelCreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TunnelCreateResponse) ProtoMessage() {}

func (x *TunnelCreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TunnelCreateResponse.ProtoReflect.Descriptor instead.
func (*TunnelCreateResponse) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{8}
}

func (x *TunnelCreateResponse) GetEnvironmentId() string {
	if x != nil {
		return x.EnvironmentId
	}
	return ""
}

func (x *TunnelCreateResponse) GetDelegate() *DockerDelegate {
	if x != nil {
		return x.Delegate
	}
	return nil
}

type StartRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EnvironmentId string                 `protobuf:"bytes,1,opt,name=environment_id,json=environmentId,proto3" json:"environment_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartRequest) Reset() {
	*x = StartRequest{}
	mi := &file_plugin_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartRequest) ProtoMessage() {}

func (x *StartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartRequest.ProtoReflect.Descriptor instead.
func (*StartRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{9}
}

func (x *StartRequest) GetEnvironmentId() string {
	if x != nil {
		return x.EnvironmentId
	}
	return ""
}

type StartResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// image_env are environment variables baked into the resolved image (e.g. a
	// Docker image's ENV). The runner layers them under the job's own variables.
	ImageEnv      map[string]string `protobuf:"bytes,1,rep,name=image_env,json=imageEnv,proto3" json:"image_env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartResponse) Reset() {
	*x = StartResponse{}
	mi := &file_plugin_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartResponse) ProtoMessage() {}

func (x *StartResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartResponse.ProtoReflect.Descriptor instead.
func (*StartResponse) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{10}
}

func (x *StartResponse) GetImageEnv() map[string]string {
	if x != nil {
		return x.ImageEnv
	}
	return nil
}

type ExecRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EnvironmentId string                 `protobuf:"bytes,1,opt,name=environment_id,json=environmentId,proto3" json:"environment_id,omitempty"`
	// command is the argv to run; command[0] is the executable.
	Command []string `protobuf:"bytes,2,rep,name=command,proto3" json:"command,omitempty"`
	// env are environment variables to set for this command.
	Env map[string]string `protobuf:"bytes,3,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// user is the user to run as, when the backend supports it (empty = default).
	User string `protobuf:"bytes,4,opt,name=user,proto3" json:"user,omitempty"`
	// workdir overrides the working directory for this command (empty = default).
	Workdir       string `protobuf:"bytes,5,opt,name=workdir,proto3" json:"workdir,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecRequest) Reset() {
	*x = ExecRequest{}
	mi := &file_plugin_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecRequest) ProtoMessage() {}

func (x *ExecRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecRequest.ProtoReflect.Descriptor instead.
func (*ExecRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{11}
}

func (x *ExecRequest) GetEnvironmentId() string {
	if x != nil {
		return x.EnvironmentId
	}
	return ""
}

func (x *ExecRequest) GetCommand() []string {
	if x != nil {
		return x.Command
	}
	return nil
}

func (x *ExecRequest) GetEnv() map[string]string {
	if x != nil {
		return x.Env
	}
	return nil
}

func (x *ExecRequest) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *ExecRequest) GetWorkdir() string {
	if x != nil {
		return x.Workdir
	}
	return ""
}

type ExecOutput struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// stream identifies which output data belongs to.
	Stream ExecOutput_Stream `protobuf:"varint,1,opt,name=stream,proto3,enum=plugin.v1.ExecOutput_Stream" json:"stream,omitempty"`
	// data is a chunk of output bytes.
	Data []byte `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	// exit_code is the command's exit status; only meaningful when done is true.
	ExitCode int32 `protobuf:"varint,3,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	// done marks the final message of the stream.
	Done bool `protobuf:"varint,4,opt,name=done,proto3" json:"done,omitempty"`
	// error_message describes a failure to run the command (as opposed to the
	// command itself failing); only meaningful when done is true.
	ErrorMessage  string `protobuf:"bytes,5,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecOutput) Reset() {
	*x = ExecOutput{}
	mi := &file_plugin_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecOutput) ProtoMessage() {}

func (x *ExecOutput) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecOutput.ProtoReflect.Descriptor instead.
func (*ExecOutput) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{12}
}

func (x *ExecOutput) GetStream() ExecOutput_Stream {
	if x != nil {
		return x.Stream
	}
	return ExecOutput_STDOUT
}

func (x *ExecOutput) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ExecOutput) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *ExecOutput) GetDone() bool {
	if x != nil {
		return x.Done
	}
	return false
}

func (x *ExecOutput) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

// CopyInChunk frames the client-streaming CopyIn RPC. The first chunk MUST set
// environment_id and dest_path; subsequent chunks carry only data. Servers MUST
// reject environment_id or dest_path on later chunks with codes.InvalidArgument.
type CopyInChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EnvironmentId string                 `protobuf:"bytes,1,opt,name=environment_id,json=environmentId,proto3" json:"environment_id,omitempty"`
	// dest_path is the directory the tar archive is extracted into.
	DestPath string `protobuf:"bytes,2,opt,name=dest_path,json=destPath,proto3" json:"dest_path,omitempty"`
	// data is a chunk of the tar archive.
	Data          []byte `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CopyInChunk) Reset() {
	*x = CopyInChunk{}
	mi := &file_plugin_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CopyInChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CopyInChunk) ProtoMessage() {}

func (x *CopyInChunk) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CopyInChunk.ProtoReflect.Descriptor instead.
func (*CopyInChunk) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{13}
}

func (x *CopyInChunk) GetEnvironmentId() string {
	if x != nil {
		return x.EnvironmentId
	}
	return ""
}

func (x *CopyInChunk) GetDestPath() string {
	if x != nil {
		return x.DestPath
	}
	return ""
}

func (x *CopyInChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type CopyInResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CopyInResponse) Reset() {
	*x = CopyInResponse{}
	mi := &file_plugin_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CopyInResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CopyInResponse) ProtoMessage() {}

func (x *CopyInResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CopyInResponse.ProtoReflect.Descriptor instead.
func (*CopyInResponse) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{14}
}

type CopyLocalRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EnvironmentId string                 `protobuf:"bytes,1,opt,name=environment_id,json=environmentId,proto3" json:"environment_id,omitempty"`
	// src_path is a path on the volume shared with the runner.
	SrcPath string `protobuf:"bytes,2,opt,name=src_path,json=srcPath,proto3" json:"src_path,omitempty"`
	// dest_path is the destination directory inside the environment.
	DestPath      string `protobuf:"bytes,3,opt,name=dest_path,json=destPath,proto3" json:"dest_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CopyLocalRequest) Reset() {
	*x = CopyLocalRequest{}
	mi := &file_plugin_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CopyLocalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CopyLocalRequest) ProtoMessage() {}

func (x *CopyLocalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CopyLocalRequest.ProtoReflect.Descriptor instead.
func (*CopyLocalRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{15}
}

func (x *CopyLocalRequest) GetEnvironmentId() string {
	if x != nil {
		return x.EnvironmentId
	}
	return ""
}

func (x *CopyLocalRequest) GetSrcPath() string {
	if x != nil {
		return x.SrcPath
	}
	return ""
}

func (x *CopyLocalRequest) GetDestPath() string {
	if x != nil {
		return x.DestPath
	}
	return ""
}

type CopyLocalResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CopyLocalResponse) Reset() {
	*x = CopyLocalResponse{}
	mi := &file_plugin_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CopyLocalResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CopyLocalResponse) ProtoMessage() {}

func (x *CopyLocalResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CopyLocalResponse.ProtoReflect.Descriptor instead.
func (*CopyLocalResponse) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{16}
}

type CopyOutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EnvironmentId string                 `protobuf:"bytes,1,opt,name=environment_id,json=environmentId,proto3" json:"environment_id,omitempty"`
	// src_path is the path inside the environment to archive and stream out.
	SrcPath       string `protobuf:"bytes,2,opt,name=src_path,json=srcPath,proto3" json:"src_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CopyOutRequest) Reset() {
	*x = CopyOutRequest{}
	mi := &file_plugin_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CopyOutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CopyOutRequest) ProtoMessage() {}

func (x *CopyOutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CopyOutRequest.ProtoReflect.Descriptor instead.
func (*CopyOutRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{17}
}

func (x *CopyOutRequest) GetEnvironmentId() string {
	if x != nil {
		return x.EnvironmentId
	}
	return ""
}

func (x *CopyOutRequest) GetSrcPath() string {
	if x != nil {
		return x.SrcPath
	}
	return ""
}

type CopyOutChunk struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// data is a chunk of the tar archive.
	Data          []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CopyOutChunk) Reset() {
	*x = CopyOutChunk{}
	mi := &file_plugin_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CopyOutChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CopyOutChunk) ProtoMessage() {}

func (x *CopyOutChunk) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CopyOutChunk.ProtoReflect.Descriptor instead.
func (*CopyOutChunk) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{18}
}

func (x *CopyOutChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type UpdateEnvRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EnvironmentId string                 `protobuf:"bytes,1,opt,name=environment_id,json=environmentId,proto3" json:"environment_id,omitempty"`
	// src_path is the env file inside the environment to read.
	SrcPath string `protobuf:"bytes,2,opt,name=src_path,json=srcPath,proto3" json:"src_path,omitempty"`
	// current_env is the runner's current view, which the file is merged over.
	CurrentEnv    map[string]string `protobuf:"bytes,3,rep,name=current_env,json=currentEnv,proto3" json:"current_env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateEnvRequest) Reset() {
	*x = UpdateEnvRequest{}
	mi := &file_plugin_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateEnvRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateEnvRequest) ProtoMessage() {}

func (x *UpdateEnvRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateEnvRequest.ProtoReflect.Descriptor instead.
func (*UpdateEnvRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{19}
}

func (x *UpdateEnvRequest) GetEnvironmentId() string {
	if x != nil {
		return x.EnvironmentId
	}
	return ""
}

func (x *UpdateEnvRequest) GetSrcPath() string {
	if x != nil {
		return x.SrcPath
	}
	return ""
}

func (x *UpdateEnvRequest) GetCurrentEnv() map[string]string {
	if x != nil {
		return x.CurrentEnv
	}
	return nil
}

type UpdateEnvResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// updated_env is current_env with the file's variables applied.
	UpdatedEnv    map[string]string `protobuf:"bytes,1,rep,name=updated_env,json=updatedEnv,proto3" json:"updated_env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateEnvResponse) Reset() {
	*x = UpdateEnvResponse{}
	mi := &file_plugin_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateEnvResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateEnvResponse) ProtoMessage() {}

func (x *UpdateEnvResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateEnvResponse.ProtoReflect.Descriptor instead.
func (*UpdateEnvResponse) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{20}
}

func (x *UpdateEnvResponse) GetUpdatedEnv() map[string]string {
	if x != nil {
		return x.UpdatedEnv
	}
	return nil
}

type IsHealthyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EnvironmentId string                 `protobuf:"bytes,1,opt,name=environment_id,json=environmentId,proto3" json:"environment_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsHealthyRequest) Reset() {
	*x = IsHealthyRequest{}
	mi := &file_plugin_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsHealthyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsHealthyRequest) ProtoMessage() {}

func (x *IsHealthyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsHealthyRequest.ProtoReflect.Descriptor instead.
func (*IsHealthyRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{21}
}

func (x *IsHealthyRequest) GetEnvironmentId() string {
	if x != nil {
		return x.EnvironmentId
	}
	return ""
}

type IsHealthyResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// wait is how long the runner should back off before checking again.
	Wait          *durationpb.Duration `protobuf:"bytes,1,opt,name=wait,proto3" json:"wait,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsHealthyResponse) Reset() {
	*x = IsHealthyResponse{}
	mi := &file_plugin_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsHealthyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsHealthyResponse) ProtoMessage() {}

func (x *IsHealthyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsHealthyResponse.ProtoReflect.Descriptor instead.
func (*IsHealthyResponse) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{22}
}

func (x *IsHealthyResponse) GetWait() *durationpb.Duration {
	if x != nil {
		return x.Wait
	}
	return nil
}

type RemoveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EnvironmentId string                 `protobuf:"bytes,1,opt,name=environment_id,json=environmentId,proto3" json:"environment_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveRequest) Reset() {
	*x = RemoveRequest{}
	mi := &file_plugin_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveRequest) ProtoMessage() {}

func (x *RemoveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveRequest.ProtoReflect.Descriptor instead.
func (*RemoveRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{23}
}

func (x *RemoveRequest) GetEnvironmentId() string {
	if x != nil {
		return x.EnvironmentId
	}
	return ""
}

type RemoveResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveResponse) Reset() {
	*x = RemoveResponse{}
	mi := &file_plugin_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveResponse) ProtoMessage() {}

func (x *RemoveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveResponse.ProtoReflect.Descriptor instead.
func (*RemoveResponse) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{24}
}

var File_plugin_proto protoreflect.FileDescriptor

const file_plugin_proto_rawDesc = "" +
	"\n" +
	"\fplugin.proto\x12\tplugin.v1\x1a\x1egoogle/protobuf/duration.proto\"\x15\n" +
	"\x13CapabilitiesRequest\"\x81\x06\n" +
	"\x14CapabilitiesResponse\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1b\n" +
	"\troot_path\x18\x02 \x01(\tR\brootPath\x12\x19\n" +
	"\bact_path\x18\x03 \x01(\tR\aactPath\x12&\n" +
	"\x0ftool_cache_path\x18\x04 \x01(\tR\rtoolCachePath\x12,\n" +
	"\x12path_variable_name\x18\x05 \x01(\tR\x10pathVariableName\x122\n" +
	"\x15default_path_variable\x18\x06 \x01(\tR\x13defaultPathVariable\x12%\n" +
	"\x0epath_separator\x18\a \x01(\tR\rpathSeparator\x126\n" +
	"\x17supports_docker_actions\x18\b \x01(\bR\x15supportsDockerActions\x124\n" +
	"\x16manages_own_networking\x18\t \x01(\bR\x14managesOwnNetworking\x12>\n" +
	"\x1bsupports_service_containers\x18\n" +
	" \x01(\bR\x19supportsServiceContainers\x12@\n" +
	"\x1cenvironment_case_insensitive\x18\v \x01(\bR\x1aenvironmentCaseInsensitive\x12Y\n" +
	"\x0erunner_context\x18\f \x03(\v22.plugin.v1.CapabilitiesResponse.RunnerContextEntryR\rrunnerContext\x12.\n" +
	"\x13supports_local_copy\x18\r \x01(\bR\x11supportsLocalCopy\x12)\n" +
	"\x10protocol_version\x18\x0f \x01(\rR\x0fprotocolVersion\x1a@\n" +
	"\x12RunnerContextEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01J\x04\b\x0e\x10\x0f\"\xc2\x01\n" +
	"\x10ServiceContainer\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05image\x18\x02 \x01(\tR\x05image\x126\n" +
	"\x03env\x18\x03 \x03(\v2$.plugin.v1.ServiceContainer.EnvEntryR\x03env\x12\x14\n" +
	"\x05ports\x18\x04 \x03(\tR\x05ports\x1a6\n" +
	"\bEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x9b\x04\n" +
	"\rCreateRequest\x12\x14\n" +
	"\x05image\x18\x01 \x01(\tR\x05image\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x123\n" +
	"\x03env\x18\x03 \x03(\v2!.plugin.v1.CreateRequest.EnvEntryR\x03env\x12\x1f\n" +
	"\vworking_dir\x18\x04 \x01(\tR\n" +
	"workingDir\x12\x17\n" +
	"\acap_add\x18\x05 \x03(\tR\x06capAdd\x12\x19\n" +
	"\bcap_drop\x18\x06 \x03(\tR\acapDrop\x127\n" +
	"\bservices\x18\a \x03(\v2\x1b.plugin.v1.ServiceContainerR\bservices\x12U\n" +
	"\x0fbackend_options\x18\b \x03(\v2,.plugin.v1.CreateRequest.BackendOptionsEntryR\x0ebackendOptions\x12\x1d\n" +
	"\n" +
	"force_pull\x18\t \x01(\bR\tforcePull\x12\x1f\n" +
	"\bplatform\x18\n" +
	" \x01(\tH\x00R\bplatform\x88\x01\x01\x1a6\n" +
	"\bEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1aA\n" +
	"\x13BackendOptionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\v\n" +
	"\t_platform\"7\n" +
	"\x0eCreateResponse\x12%\n" +
	"\x0eenvironment_id\x18\x01 \x01(\tR\renvironmentId\"\xb0\x01\n" +
	"\x0eDockerDelegate\x12\x1a\n" +
	"\bendpoint\x18\x01 \x01(\tR\bendpoint\x12\x15\n" +
	"\x06tls_ca\x18\x02 \x01(\fR\x05tlsCa\x12\x19\n" +
	"\btls_cert\x18\x03 \x01(\fR\atlsCert\x12\x17\n" +
	"\atls_key\x18\x04 \x01(\fR\x06tlsKey\x127\n" +
	"\x18tls_insecure_skip_verify\x18\x05 \x01(\bR\x15tlsInsecureSkipVerify\"[\n" +
	"\x1aTunnelCapabilitiesResponse\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12)\n" +
	"\x10protocol_version\x18\x02 \x01(\rR\x0fprotocolVersion\"\x82\x02\n" +
	"\x13TunnelCreateRequest\x12[\n" +
	"\x0fbackend_options\x18\x01 \x03(\v22.plugin.v1.TunnelCreateRequest.BackendOptionsEntryR\x0ebackendOptions\x12\x1f\n" +
	"\bplatform\x18\x02 \x01(\tH\x00R\bplatform\x88\x01\x01\x12\x1d\n" +
	"\n" +
	"force_pull\x18\x03 \x01(\bR\tforcePull\x1aA\n" +
	"\x13BackendOptionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\v\n" +
	"\t_platform\"t\n" +
	"\x14TunnelCreateResponse\x12%\n" +
	"\x0eenvironment_id\x18\x01 \x01(\tR\renvironmentId\x125\n" +
	"\bdelegate\x18\x02 \x01(\v2\x19.plugin.v1.DockerDelegateR\bdelegate\"5\n" +
	"\fStartRequest\x12%\n" +
	"\x0eenvironment_id\x18\x01 \x01(\tR\renvironmentId\"\x91\x01\n" +
	"\rStartResponse\x12C\n" +
	"\timage_env\x18\x01 \x03(\v2&.plugin.v1.StartResponse.ImageEnvEntryR\bimageEnv\x1a;\n" +
	"\rImageEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xe7\x01\n" +
	"\vExecRequest\x12%\n" +
	"\x0eenvironment_id\x18\x01 \x01(\tR\renvironmentId\x12\x18\n" +
	"\acommand\x18\x02 \x03(\tR\acommand\x121\n" +
	"\x03env\x18\x03 \x03(\v2\x1f.plugin.v1.ExecRequest.EnvEntryR\x03env\x12\x12\n" +
	"\x04user\x18\x04 \x01(\tR\x04user\x12\x18\n" +
	"\aworkdir\x18\x05 \x01(\tR\aworkdir\x1a6\n" +
	"\bEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xce\x01\n" +
	"\n" +
	"ExecOutput\x124\n" +
	"\x06stream\x18\x01 \x01(\x0e2\x1c.plugin.v1.ExecOutput.StreamR\x06stream\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\x12\x1b\n" +
	"\texit_code\x18\x03 \x01(\x05R\bexitCode\x12\x12\n" +
	"\x04done\x18\x04 \x01(\bR\x04done\x12#\n" +
	"\rerror_message\x18\x05 \x01(\tR\ferrorMessage\" \n" +
	"\x06Stream\x12\n" +
	"\n" +
	"\x06STDOUT\x10\x00\x12\n" +
	"\n" +
	"\x06STDERR\x10\x01\"e\n" +
	"\vCopyInChunk\x12%\n" +
	"\x0eenvironment_id\x18\x01 \x01(\tR\renvironmentId\x12\x1b\n" +
	"\tdest_path\x18\x02 \x01(\tR\bdestPath\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\"\x10\n" +
	"\x0eCopyInResponse\"q\n" +
	"\x10CopyLocalRequest\x12%\n" +
	"\x0eenvironment_id\x18\x01 \x01(\tR\renvironmentId\x12\x19\n" +
	"\bsrc_path\x18\x02 \x01(\tR\asrcPath\x12\x1b\n" +
	"\tdest_path\x18\x03 \x01(\tR\bdestPath\"\x13\n" +
	"\x11CopyLocalResponse\"R\n" +
	"\x0eCopyOutRequest\x12%\n" +
	"\x0eenvironment_id\x18\x01 \x01(\tR\renvironmentId\x12\x19\n" +
	"\bsrc_path\x18\x02 \x01(\tR\asrcPath\"\"\n" +
	"\fCopyOutChunk\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\"\xe1\x01\n" +
	"\x10UpdateEnvRequest\x12%\n" +
	"\x0eenvironment_id\x18\x01 \x01(\tR\renvironmentId\x12\x19\n" +
	"\bsrc_path\x18\x02 \x01(\tR\asrcPath\x12L\n" +
	"\vcurrent_env\x18\x03 \x03(\v2+.plugin.v1.UpdateEnvRequest.CurrentEnvEntryR\n" +
	"currentEnv\x1a=\n" +
	"\x0fCurrentEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xa1\x01\n" +
	"\x11UpdateEnvResponse\x12M\n" +
	"\vupdated_env\x18\x01 \x03(\v2,.plugin.v1.UpdateEnvResponse.UpdatedEnvEntryR\n" +
	"updatedEnv\x1a=\n" +
	"\x0fUpdatedEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"9\n" +
	"\x10IsHealthyRequest\x12%\n" +
	"\x0eenvironment_id\x18\x01 \x01(\tR\renvironmentId\"B\n" +
	"\x11IsHealthyResponse\x12-\n" +
	"\x04wait\x18\x01 \x01(\v2\x19.google.protobuf.DurationR\x04wait\"6\n" +
	"\rRemoveRequest\x12%\n" +
	"\x0eenvironment_id\x18\x01 \x01(\tR\renvironmentId\"\x10\n" +
	"\x0eRemoveResponse2\xab\x05\n" +
	"\rBackendPlugin\x12O\n" +
	"\fCapabilities\x12\x1e.plugin.v1.CapabilitiesRequest\x1a\x1f.plugin.v1.CapabilitiesResponse\x12=\n" +
	"\x06Create\x12\x18.plugin.v1.CreateRequest\x1a\x19.plugin.v1.CreateResponse\x12:\n" +
	"\x05Start\x12\x17.plugin.v1.StartRequest\x1a\x18.plugin.v1.StartResponse\x127\n" +
	"\x04Exec\x12\x16.plugin.v1.ExecRequest\x1a\x15.plugin.v1.ExecOutput0\x01\x12=\n" +
	"\x06CopyIn\x12\x16.plugin.v1.CopyInChunk\x1a\x19.plugin.v1.CopyInResponse(\x01\x12F\n" +
	"\tCopyLocal\x12\x1b.plugin.v1.CopyLocalRequest\x1a\x1c.plugin.v1.CopyLocalResponse\x12?\n" +
	"\aCopyOut\x12\x19.plugin.v1.CopyOutRequest\x1a\x17.plugin.v1.CopyOutChunk0\x01\x12F\n" +
	"\tUpdateEnv\x12\x1b.plugin.v1.UpdateEnvRequest\x1a\x1c.plugin.v1.UpdateEnvResponse\x12F\n" +
	"\tIsHealthy\x12\x1b.plugin.v1.IsHealthyRequest\x1a\x1c.plugin.v1.IsHealthyResponse\x12=\n" +
	"\x06Remove\x12\x18.plugin.v1.RemoveRequest\x1a\x19.plugin.v1.RemoveResponse2\xf5\x01\n" +
	"\x12DockerTunnelPlugin\x12U\n" +
	"\fCapabilities\x12\x1e.plugin.v1.CapabilitiesRequest\x1a%.plugin.v1.TunnelCapabilitiesResponse\x12I\n" +
	"\x06Create\x12\x1e.plugin.v1.TunnelCreateRequest\x1a\x1f.plugin.v1.TunnelCreateResponse\x12=\n" +
	"\x06Remove\x12\x18.plugin.v1.RemoveRequest\x1a\x19.plugin.v1.RemoveResponseBBZ@code.forgejo.org/forgejo/runner/v12/act/plugin/proto/v1;pluginv1b\x06proto3"

var (
	file_plugin_proto_rawDescOnce sync.Once
	file_plugin_proto_rawDescData []byte
)

func file_plugin_proto_rawDescGZIP() []byte {
	file_plugin_proto_rawDescOnce.Do(func() {
		file_plugin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_plugin_proto_rawDesc), len(file_plugin_proto_rawDesc)))
	})
	return file_plugin_proto_rawDescData
}

var (
	file_plugin_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
	file_plugin_proto_msgTypes  = make([]protoimpl.MessageInfo, 34)
	file_plugin_proto_goTypes   = []any{
		ExecOutput_Stream(0),               // 0: plugin.v1.ExecOutput.Stream
		(*CapabilitiesRequest)(nil),        // 1: plugin.v1.CapabilitiesRequest
		(*CapabilitiesResponse)(nil),       // 2: plugin.v1.CapabilitiesResponse
		(*ServiceContainer)(nil),           // 3: plugin.v1.ServiceContainer
		(*CreateRequest)(nil),              // 4: plugin.v1.CreateRequest
		(*CreateResponse)(nil),             // 5: plugin.v1.CreateResponse
		(*DockerDelegate)(nil),             // 6: plugin.v1.DockerDelegate
		(*TunnelCapabilitiesResponse)(nil), // 7: plugin.v1.TunnelCapabilitiesResponse
		(*TunnelCreateRequest)(nil),        // 8: plugin.v1.TunnelCreateRequest
		(*TunnelCreateResponse)(nil),       // 9: plugin.v1.TunnelCreateResponse
		(*StartRequest)(nil),               // 10: plugin.v1.StartRequest
		(*StartResponse)(nil),              // 11: plugin.v1.StartResponse
		(*ExecRequest)(nil),                // 12: plugin.v1.ExecRequest
		(*ExecOutput)(nil),                 // 13: plugin.v1.ExecOutput
		(*CopyInChunk)(nil),                // 14: plugin.v1.CopyInChunk
		(*CopyInResponse)(nil),             // 15: plugin.v1.CopyInResponse
		(*CopyLocalRequest)(nil),           // 16: plugin.v1.CopyLocalRequest
		(*CopyLocalResponse)(nil),          // 17: plugin.v1.CopyLocalResponse
		(*CopyOutRequest)(nil),             // 18: plugin.v1.CopyOutRequest
		(*CopyOutChunk)(nil),               // 19: plugin.v1.CopyOutChunk
		(*UpdateEnvRequest)(nil),           // 20: plugin.v1.UpdateEnvRequest
		(*UpdateEnvResponse)(nil),          // 21: plugin.v1.UpdateEnvResponse
		(*IsHealthyRequest)(nil),           // 22: plugin.v1.IsHealthyRequest
		(*IsHealthyResponse)(nil),          // 23: plugin.v1.IsHealthyResponse
		(*RemoveRequest)(nil),              // 24: plugin.v1.RemoveRequest
		(*RemoveResponse)(nil),             // 25: plugin.v1.RemoveResponse
		nil,                                // 26: plugin.v1.CapabilitiesResponse.RunnerContextEntry
		nil,                                // 27: plugin.v1.ServiceContainer.EnvEntry
		nil,                                // 28: plugin.v1.CreateRequest.EnvEntry
		nil,                                // 29: plugin.v1.CreateRequest.BackendOptionsEntry
		nil,                                // 30: plugin.v1.TunnelCreateRequest.BackendOptionsEntry
		nil,                                // 31: plugin.v1.StartResponse.ImageEnvEntry
		nil,                                // 32: plugin.v1.ExecRequest.EnvEntry
		nil,                                // 33: plugin.v1.UpdateEnvRequest.CurrentEnvEntry
		nil,                                // 34: plugin.v1.UpdateEnvResponse.UpdatedEnvEntry
		(*durationpb.Duration)(nil),        // 35: google.protobuf.Duration
	}
)

var file_plugin_proto_depIdxs = []int32{
	26, // 0: plugin.v1.CapabilitiesResponse.runner_context:type_name -> plugin.v1.CapabilitiesResponse.RunnerContextEntry
	27, // 1: plugin.v1.ServiceContainer.env:type_name -> plugin.v1.ServiceContainer.EnvEntry
	28, // 2: plugin.v1.CreateRequest.env:type_name -> plugin.v1.CreateRequest.EnvEntry
	3,  // 3: plugin.v1.CreateRequest.services:type_name -> plugin.v1.ServiceContainer
	29, // 4: plugin.v1.CreateRequest.backend_options:type_name -> plugin.v1.CreateRequest.BackendOptionsEntry
	30, // 5: plugin.v1.TunnelCreateRequest.backend_options:type_name -> plugin.v1.TunnelCreateRequest.BackendOptionsEntry
	6,  // 6: plugin.v1.TunnelCreateResponse.delegate:type_name -> plugin.v1.DockerDelegate
	31, // 7: plugin.v1.StartResponse.image_env:type_name -> plugin.v1.StartResponse.ImageEnvEntry
	32, // 8: plugin.v1.ExecRequest.env:type_name -> plugin.v1.ExecRequest.EnvEntry
	0,  // 9: plugin.v1.ExecOutput.stream:type_name -> plugin.v1.ExecOutput.Stream
	33, // 10: plugin.v1.UpdateEnvRequest.current_env:type_name -> plugin.v1.UpdateEnvRequest.CurrentEnvEntry
	34, // 11: plugin.v1.UpdateEnvResponse.updated_env:type_name -> plugin.v1.UpdateEnvResponse.UpdatedEnvEntry
	35, // 12: plugin.v1.IsHealthyResponse.wait:type_name -> google.protobuf.Duration
	1,  // 13: plugin.v1.BackendPlugin.Capabilities:input_type -> plugin.v1.CapabilitiesRequest
	4,  // 14: plugin.v1.BackendPlugin.Create:input_type -> plugin.v1.CreateRequest
	10, // 15: plugin.v1.BackendPlugin.Start:input_type -> plugin.v1.StartRequest
	12, // 16: plugin.v1.BackendPlugin.Exec:input_type -> plugin.v1.ExecRequest
	14, // 17: plugin.v1.BackendPlugin.CopyIn:input_type -> plugin.v1.CopyInChunk
	16, // 18: plugin.v1.BackendPlugin.CopyLocal:input_type -> plugin.v1.CopyLocalRequest
	18, // 19: plugin.v1.BackendPlugin.CopyOut:input_type -> plugin.v1.CopyOutRequest
	20, // 20: plugin.v1.BackendPlugin.UpdateEnv:input_type -> plugin.v1.UpdateEnvRequest
	22, // 21: plugin.v1.BackendPlugin.IsHealthy:input_type -> plugin.v1.IsHealthyRequest
	24, // 22: plugin.v1.BackendPlugin.Remove:input_type -> plugin.v1.RemoveRequest
	1,  // 23: plugin.v1.DockerTunnelPlugin.Capabilities:input_type -> plugin.v1.CapabilitiesRequest
	8,  // 24: plugin.v1.DockerTunnelPlugin.Create:input_type -> plugin.v1.TunnelCreateRequest
	24, // 25: plugin.v1.DockerTunnelPlugin.Remove:input_type -> plugin.v1.RemoveRequest
	2,  // 26: plugin.v1.BackendPlugin.Capabilities:output_type -> plugin.v1.CapabilitiesResponse
	5,  // 27: plugin.v1.BackendPlugin.Create:output_type -> plugin.v1.CreateResponse
	11, // 28: plugin.v1.BackendPlugin.Start:output_type -> plugin.v1.StartResponse
	13, // 29: plugin.v1.BackendPlugin.Exec:output_type -> plugin.v1.ExecOutput
	15, // 30: plugin.v1.BackendPlugin.CopyIn:output_type -> plugin.v1.CopyInResponse
	17, // 31: plugin.v1.BackendPlugin.CopyLocal:output_type -> plugin.v1.CopyLocalResponse
	19, // 32: plugin.v1.BackendPlugin.CopyOut:output_type -> plugin.v1.CopyOutChunk
	21, // 33: plugin.v1.BackendPlugin.UpdateEnv:output_type -> plugin.v1.UpdateEnvResponse
	23, // 34: plugin.v1.BackendPlugin.IsHealthy:output_type -> plugin.v1.IsHealthyResponse
	25, // 35: plugin.v1.BackendPlugin.Remove:output_type -> plugin.v1.RemoveResponse
	7,  // 36: plugin.v1.DockerTunnelPlugin.Capabilities:output_type -> plugin.v1.TunnelCapabilitiesResponse
	9,  // 37: plugin.v1.DockerTunnelPlugin.Create:output_type -> plugin.v1.TunnelCreateResponse
	25, // 38: plugin.v1.DockerTunnelPlugin.Remove:output_type -> plugin.v1.RemoveResponse
	26, // [26:39] is the sub-list for method output_type
	13, // [13:26] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_plugin_proto_init() }
func file_plugin_proto_init() {
	if File_plugin_proto != nil {
		return
	}
	file_plugin_proto_msgTypes[3].OneofWrappers = []any{}
	file_plugin_proto_msgTypes[7].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_plugin_proto_rawDesc), len(file_plugin_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   34,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_plugin_proto_goTypes,
		DependencyIndexes: file_plugin_proto_depIdxs,
		EnumInfos:         file_plugin_proto_enumTypes,
		MessageInfos:      file_plugin_proto_msgTypes,
	}.Build()
	File_plugin_proto = out.File
	file_plugin_proto_goTypes = nil
	file_plugin_proto_depIdxs = nil
}
